apiVersion: v1
kind: ReplicationController
metadata:
  namespace: sre
  creationTimestamp: null
  name: mysql
  labels:
    name: mysql
spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: apollp-mysql

      restartPolicy: Always
      volumes:
        - name: apollp-mysql
          hostPath:
            path: /Users/wendi/Desktop/workspace/workspace1/db/apollo



---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: sre
  labels:
    name: mysql-service
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql





# ---
# kind: Service
# apiVersion: v1
# metadata:
#   namespace: sre
#   name: service-mysql-for-apollo-prod-env
#   labels:
#     app: service-mysql-for-apollo-prod-env
# spec:
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#   type: ClusterIP
#   sessionAffinity: None

# ---
# kind: Endpoints
# apiVersion: v1
# metadata:
#   namespace: sre
#   name: service-mysql-for-apollo-prod-env
# subsets:
#   - addresses:
#       - ip: 192.168.1.101
#     ports:
#       - protocol: TCP
#         port: 3306

